name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to Server
      run: rsync -avz --delete dist/ user@your-server-ip:/path/to/web/directory
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
